[package]
name = "test_test"
version = "0.1.0"
authors = ["xmmmmmovo <13256172360@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# 这里省略了标准的 crate 数据
[dev-dependencies]
pretty_assertions = "0.4.0"