[package]
name = "misc"
version = "0.1.0"
authors = ["xmmmmmovo <13256172360@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
