[workspace]
members = [
    "learn_option",
    "learn_enum",
    "learn_owner",
    "learn_struct",
    "learn_hashmap",
    "learn_create",
    "learn_create4",
    "learn_err1",
    "learn_test",
]
