[workspace]

members = [
    "Introduction/Getting started/*/",
    "Common Programming Concepts/Variables/*/",
    "Common Programming Concepts/Data Types/*/",
    "Common Programming Concepts/Functions/*/",
    "Common Programming Concepts/Variables and Functions Test/*/",
    "Common Programming Concepts/If/*/",
    "Writing Automated Tests/Tests/*/",
    "Writing Automated Tests/Tests Test/*/",
    "Common Collections/Strings/*/",
    "Common Collections/String Test/*/",
    "Modules and Macros/Modules/*/",
    "Modules and Macros/Macros/*/",
    "Modules and Macros/Macros and Modules Test/*/",
    "Understanding Ownership/Move Semantics/*/",
    "Recoverable and Unrecoverable Errors/Error Handling/*/",
    "Fearless Concurrency/Threads/*/",
    "Iterators and Closures/Standard Library Types/*/"
]

exclude = [
    "**/*.yaml"
]
